# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jeniusCrud' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jeniusCrud
  pod 'AlamofireObjectMapper', '~> 5.0.0'
  pod 'Alamofire', '~> 4.7.2'
  pod 'Kingfisher', '~> 4.10.1'

end
